const mongoose = require('mongoose');
require('dotenv').config();

const Product = require('../models/Product');

const products = [
    // =============================================================
    //  WOMEN'S — SAREES
    // =============================================================
    { name: 'Banarasi Silk Saree', description: 'Exquisite handwoven Banarasi silk saree with intricate gold zari work. Rich pallu with traditional motifs. Perfect for weddings and festivals.', price: 8999, originalPrice: 12999, category: 'women', subcategory: 'sarees', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400', rating: 4.8, reviewCount: 856, sizes: ['Free Size'], colors: ['Red & Gold', 'Maroon & Gold', 'Royal Blue'], inStock: true, featured: true, tags: ['banarasi', 'silk', 'wedding', 'zari', 'handwoven'] },
    { name: 'Kanjivaram Pure Silk Saree', description: 'Authentic Kanjivaram saree from Tamil Nadu. Pure mulberry silk with contrast border and grand pallu. Temple jewellery inspired motifs.', price: 15999, originalPrice: 21999, category: 'women', subcategory: 'sarees', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.9, reviewCount: 1234, sizes: ['Free Size'], colors: ['Purple & Gold', 'Green & Maroon', 'Red & Green'], inStock: true, featured: true, tags: ['kanjivaram', 'silk', 'bridal', 'traditional', 'temple'] },
    { name: 'Chanderi Cotton Saree', description: 'Lightweight Chanderi cotton saree with delicate butis. Sheer texture with golden border. Ideal for summer and daily puja wear.', price: 2499, originalPrice: 3499, category: 'women', subcategory: 'sarees', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.4, reviewCount: 567, sizes: ['Free Size'], colors: ['Yellow', 'Peach', 'Mint Green'], inStock: true, featured: false, tags: ['chanderi', 'cotton', 'lightweight', 'daily-wear'] },
    { name: 'Pochampally Ikat Saree', description: 'Handloom Pochampally Ikat saree with geometric patterns. Double ikat weave from Telangana. GI tagged authentic craft.', price: 4599, originalPrice: null, category: 'women', subcategory: 'sarees', brand: 'Handloom House', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400', rating: 4.5, reviewCount: 389, sizes: ['Free Size'], colors: ['Red & White', 'Blue & White', 'Green & Yellow'], inStock: true, featured: false, tags: ['pochampally', 'ikat', 'handloom', 'telangana'] },
    { name: 'Mysore Crepe Silk Saree', description: 'Elegant Mysore crepe silk saree with minimal design. Lightweight and easy to drape. Perfect for office and casual occasions.', price: 3999, originalPrice: 5499, category: 'women', subcategory: 'sarees', brand: 'Mysore Silks', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.3, reviewCount: 445, sizes: ['Free Size'], colors: ['Navy Blue', 'Wine', 'Teal'], inStock: true, featured: false, tags: ['mysore', 'crepe', 'silk', 'office-wear'] },
    { name: 'Paithani Silk Saree', description: 'Maharashtra special Paithani saree with peacock pallu. Handwoven with real zari. Heirloom quality bridal saree.', price: 24999, originalPrice: 34999, category: 'women', subcategory: 'sarees', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.9, reviewCount: 234, sizes: ['Free Size'], colors: ['Green & Red', 'Purple & Gold'], inStock: true, featured: true, tags: ['paithani', 'bridal', 'heirloom', 'maharashtra'] },

    // =============================================================
    //  WOMEN'S — LEHENGAS
    // =============================================================
    { name: 'Bridal Lehenga Choli Set', description: 'Stunning bridal lehenga in heavy raw silk with intricate embroidery, sequin and stone work. Includes matching choli and net dupatta.', price: 18999, originalPrice: 29999, category: 'women', subcategory: 'lehengas', brand: 'Sabyasachi Style', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.7, reviewCount: 678, sizes: ['S', 'M', 'L', 'XL'], colors: ['Red', 'Maroon', 'Pink'], inStock: true, featured: true, tags: ['bridal', 'lehenga', 'wedding', 'embroidery'] },
    { name: 'Designer Mirror Work Lehenga', description: 'Rajasthani mirror work lehenga with vibrant colours. Ghagra style with flared silhouette. Festival special.', price: 7999, originalPrice: 11999, category: 'women', subcategory: 'lehengas', brand: 'Rajwada Fashion', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.5, reviewCount: 345, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Orange', 'Blue', 'Green'], inStock: true, featured: false, tags: ['mirror-work', 'rajasthani', 'festival', 'ghagra'] },
    { name: 'Pastel Party Wear Lehenga', description: 'Elegant pastel lehenga with thread embroidery and sequin highlights. Modern cut with crop top style blouse.', price: 5999, originalPrice: null, category: 'women', subcategory: 'lehengas', brand: 'Meena Bazaar', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.3, reviewCount: 267, sizes: ['XS', 'S', 'M', 'L'], colors: ['Lavender', 'Mint', 'Peach'], inStock: true, featured: false, tags: ['pastel', 'party-wear', 'modern', 'crop-top'] },

    // =============================================================
    //  WOMEN'S — SALWAR SUITS
    // =============================================================
    { name: 'Anarkali Suit with Dupatta', description: 'Floor-length Anarkali suit in georgette with heavy gota patti work. Comes with churidar and matching dupatta.', price: 4999, originalPrice: 6999, category: 'women', subcategory: 'salwar-suits', brand: 'Meena Bazaar', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.6, reviewCount: 534, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Wine', 'Teal', 'Mustard'], inStock: true, featured: true, tags: ['anarkali', 'gota-patti', 'festive'] },
    { name: 'Patiala Salwar Suit Set', description: 'Punjabi style Patiala suit with printed kurta and contrast Patiala salwar. Comfortable cotton blend.', price: 1999, originalPrice: 2999, category: 'women', subcategory: 'salwar-suits', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.2, reviewCount: 445, sizes: ['S', 'M', 'L', 'XL'], colors: ['Yellow & Blue', 'Pink & Green', 'Red & Black'], inStock: true, featured: false, tags: ['patiala', 'punjabi', 'cotton', 'daily-wear'] },
    { name: 'Palazzo Suit Set', description: 'Trendy palazzo suit with embroidered kurta and wide-leg palazzo. Includes chiffon dupatta with lace border.', price: 2799, originalPrice: null, category: 'women', subcategory: 'salwar-suits', brand: 'W for Woman', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.4, reviewCount: 378, sizes: ['S', 'M', 'L', 'XL'], colors: ['White & Gold', 'Navy & Silver', 'Black & Red'], inStock: true, featured: false, tags: ['palazzo', 'trendy', 'chiffon', 'lace'] },

    // =============================================================
    //  WOMEN'S — KURTIS
    // =============================================================
    { name: 'Chikankari Cotton Kurti', description: 'Lucknowi Chikankari hand-embroidered kurti in soft cotton. Delicate floral patterns with scalloped hem.', price: 1499, originalPrice: 2199, category: 'women', subcategory: 'kurtis', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.5, reviewCount: 789, sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Peach', 'Sky Blue'], inStock: true, featured: true, tags: ['chikankari', 'lucknowi', 'cotton', 'embroidered'] },
    { name: 'Straight Cut Rayon Kurti', description: 'Comfortable straight-cut kurti in premium rayon. Block print design with mandarin collar. Perfect for office wear.', price: 899, originalPrice: null, category: 'women', subcategory: 'kurtis', brand: 'W for Woman', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.1, reviewCount: 1234, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Mustard', 'Olive', 'Maroon'], inStock: true, featured: false, tags: ['rayon', 'office-wear', 'block-print', 'daily'] },
    { name: 'Designer Anarkali Kurti', description: 'Flared Anarkali style kurti with gold prints and tassel details. Festive wear in premium georgette fabric.', price: 1999, originalPrice: 2799, category: 'women', subcategory: 'kurtis', brand: 'Biba', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.4, reviewCount: 456, sizes: ['S', 'M', 'L', 'XL'], colors: ['Red', 'Navy', 'Emerald Green'], inStock: true, featured: false, tags: ['anarkali', 'festive', 'georgette', 'designer'] },

    // =============================================================
    //  WOMEN'S — DUPATTAS & BLOUSES
    // =============================================================
    { name: 'Bandhani Silk Dupatta', description: 'Traditional Rajasthani Bandhani dupatta in pure silk. Vibrant tie-dye pattern with golden border.', price: 1299, originalPrice: 1899, category: 'women', subcategory: 'dupattas', brand: 'Rajwada Fashion', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.3, reviewCount: 234, sizes: ['Free Size'], colors: ['Red & Yellow', 'Green & Orange', 'Pink & Purple'], inStock: true, featured: false, tags: ['bandhani', 'rajasthani', 'silk', 'traditional'] },
    { name: 'Embroidered Readymade Blouse', description: 'Designer readymade blouse with zardozi embroidery. Padded with back hooks. Pairs perfectly with silk sarees.', price: 1599, originalPrice: null, category: 'women', subcategory: 'blouses', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400', rating: 4.2, reviewCount: 345, sizes: ['32', '34', '36', '38', '40'], colors: ['Gold', 'Red', 'Green', 'Black'], inStock: true, featured: false, tags: ['blouse', 'zardozi', 'readymade', 'designer'] },

    // =============================================================
    //  WOMEN'S — JEWELLERY
    // =============================================================
    { name: 'Temple Jewellery Set', description: 'South Indian temple jewellery set with necklace, earrings and tikka. Gold-plated with ruby and emerald stones.', price: 2999, originalPrice: 4499, category: 'women', subcategory: 'jewellery', brand: 'Tanishq Style', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400', rating: 4.6, reviewCount: 567, sizes: [], colors: ['Gold & Ruby', 'Gold & Emerald'], inStock: true, featured: true, tags: ['temple', 'jewellery', 'south-indian', 'gold-plated'] },
    { name: 'Kundan Choker Necklace', description: 'Royal Kundan choker with meenakari work on reverse. Bridal jewellery with matching jhumka earrings.', price: 3499, originalPrice: null, category: 'women', subcategory: 'jewellery', brand: 'Tanishq Style', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400', rating: 4.7, reviewCount: 389, sizes: [], colors: ['Gold & Polki', 'Gold & Pearl'], inStock: true, featured: false, tags: ['kundan', 'choker', 'bridal', 'meenakari'] },
    { name: 'Oxidised Silver Jhumka Set', description: 'Trendy oxidised silver jhumka earrings with ghungroo details. Lightweight and perfect for Indo-western fusion looks.', price: 499, originalPrice: 799, category: 'women', subcategory: 'jewellery', brand: 'Silver Street', image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400', rating: 4.4, reviewCount: 1456, sizes: [], colors: ['Oxidised Silver', 'Antique Gold'], inStock: true, featured: false, tags: ['oxidised', 'jhumka', 'fusion', 'trendy'] },

    // =============================================================
    //  WOMEN'S — FOOTWEAR & ACCESSORIES
    // =============================================================
    { name: 'Embroidered Juttis for Women', description: 'Handcrafted Punjabi juttis with colourful embroidery. Cushioned sole for comfort. Goes with kurtis and sarees.', price: 999, originalPrice: 1499, category: 'women', subcategory: 'footwear', brand: 'Rajwada Fashion', image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400', rating: 4.5, reviewCount: 567, sizes: ['4', '5', '6', '7', '8', '9'], colors: ['Multi', 'Red & Gold', 'Pink & Green'], inStock: true, featured: false, tags: ['juttis', 'punjabi', 'embroidered', 'handcrafted'] },
    { name: 'Payal Anklets (Pair)', description: 'Traditional silver-toned payal anklets with ghungroo bells. Musical tinkling sound. Adjustable size.', price: 399, originalPrice: 599, category: 'women', subcategory: 'accessories', brand: 'Silver Street', image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400', rating: 4.4, reviewCount: 890, sizes: [], colors: ['Silver', 'Antique Silver'], inStock: true, featured: false, tags: ['payal', 'anklets', 'ghungroo', 'traditional'] },

    // =============================================================
    //  MEN'S — KURTAS
    // =============================================================
    { name: 'Silk Kurta Pajama Set', description: 'Premium silk kurta with churidar pajama. Subtle self-design with golden buttons. Wedding and festive essential.', price: 3999, originalPrice: 5999, category: 'men', subcategory: 'kurtas', brand: 'Manyavar', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.6, reviewCount: 678, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Cream', 'Gold', 'Maroon'], inStock: true, featured: true, tags: ['silk', 'kurta-pajama', 'wedding', 'festive'] },
    { name: 'Cotton Pathani Kurta', description: 'Comfortable cotton Pathani suit with side-slit kurta and matching salwar. Ideal for Eid and casual occasions.', price: 1799, originalPrice: 2499, category: 'men', subcategory: 'kurtas', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.3, reviewCount: 534, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Black', 'Navy'], inStock: true, featured: false, tags: ['pathani', 'cotton', 'casual', 'eid'] },
    { name: 'Linen Short Kurta', description: 'Modern short kurta in pure linen with Chinese collar. Minimalist design for everyday wear. Pairs with jeans or chinos.', price: 1299, originalPrice: null, category: 'men', subcategory: 'kurtas', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.4, reviewCount: 890, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Sky Blue', 'Olive'], inStock: true, featured: false, tags: ['linen', 'short-kurta', 'casual', 'modern'] },
    { name: 'Lucknowi Chikan Kurta', description: 'Hand-embroidered Lucknowi chikankari kurta in fine cotton. Traditional craft with modern fit. Festival ready.', price: 2499, originalPrice: 3499, category: 'men', subcategory: 'kurtas', brand: 'Manyavar', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.5, reviewCount: 456, sizes: ['M', 'L', 'XL', 'XXL'], colors: ['White', 'Peach', 'Powder Blue'], inStock: true, featured: true, tags: ['chikankari', 'lucknowi', 'handloom', 'festival'] },

    // =============================================================
    //  MEN'S — SHERWANIS
    // =============================================================
    { name: 'Royal Embroidered Sherwani', description: 'Grand sherwani with heavy thread and zardozi embroidery. Includes churidar and stole. Groom collection.', price: 12999, originalPrice: 19999, category: 'men', subcategory: 'sherwanis', brand: 'Manyavar', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400', rating: 4.8, reviewCount: 345, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Ivory', 'Gold', 'Maroon'], inStock: true, featured: true, tags: ['sherwani', 'groom', 'wedding', 'embroidered', 'zardozi'] },
    { name: 'Jodhpuri Bandhgala Sherwani', description: 'Sleek Jodhpuri style Bandhgala sherwani in jacquard fabric. Prince collar with concealed buttons. Royal Rajasthani feel.', price: 8999, originalPrice: 13499, category: 'men', subcategory: 'sherwanis', brand: 'Rajwada Fashion', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400', rating: 4.6, reviewCount: 267, sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Black', 'Navy', 'Wine'], inStock: true, featured: false, tags: ['jodhpuri', 'bandhgala', 'jacquard', 'formal'] },

    // =============================================================
    //  MEN'S — CASUAL SHIRTS & PANTS
    // =============================================================
    { name: 'Mandarin Collar Casual Shirt', description: 'Trendy mandarin collar shirt in premium cotton. Rolled-up sleeve tabs with contrast inner collar. Smart casual essential.', price: 1299, originalPrice: 1799, category: 'men', subcategory: 'shirts', brand: 'Peter England', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400', rating: 4.2, reviewCount: 789, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Blue', 'Black'], inStock: true, featured: false, tags: ['mandarin', 'casual', 'cotton', 'smart'] },
    { name: 'Printed Half-Sleeve Shirt', description: 'Tropical print half-sleeve shirt in lyocell fabric. Relaxed fit for weekend outings and beach vibes.', price: 999, originalPrice: null, category: 'men', subcategory: 'shirts', brand: 'Allen Solly', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400', rating: 4.0, reviewCount: 567, sizes: ['S', 'M', 'L', 'XL'], colors: ['Blue Print', 'Green Print', 'Maroon Print'], inStock: true, featured: false, tags: ['printed', 'casual', 'half-sleeve', 'lyocell'] },
    { name: 'Slim Fit Chino Trousers', description: 'Smart slim-fit chinos in stretch cotton. Versatile trouser for office and casual wear. Ankle length.', price: 1499, originalPrice: 1999, category: 'men', subcategory: 'pants', brand: 'Peter England', image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400', rating: 4.3, reviewCount: 634, sizes: ['28', '30', '32', '34', '36', '38'], colors: ['Khaki', 'Navy', 'Olive', 'Black'], inStock: true, featured: false, tags: ['chino', 'slim-fit', 'office', 'stretch'] },
    { name: 'Relaxed Fit Cargo Joggers', description: 'Comfortable cargo joggers with multiple pockets. Elastic waist and cuffed ankles. Weekend essential.', price: 1199, originalPrice: null, category: 'men', subcategory: 'pants', brand: 'Allen Solly', image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400', rating: 4.4, reviewCount: 456, sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Grey', 'Olive'], inStock: true, featured: false, tags: ['cargo', 'joggers', 'casual', 'comfort'] },
    { name: 'Classic Denim Jeans', description: 'Mid-rise straight fit jeans in dark indigo wash. Premium denim with slight stretch for comfort all day.', price: 1799, originalPrice: 2499, category: 'men', subcategory: 'jeans', brand: 'Levi Strauss', image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400', rating: 4.5, reviewCount: 1567, sizes: ['28', '30', '32', '34', '36', '38'], colors: ['Dark Indigo', 'Black', 'Light Wash'], inStock: true, featured: true, tags: ['denim', 'jeans', 'classic', 'stretch'] },

    // =============================================================
    //  MEN'S — LUNGIS & DHOTIS
    // =============================================================
    { name: 'Cotton Lungi (Mundu)', description: 'Premium Kerala style cotton mundu with golden kasavu border. Double-layered for daily and temple wear.', price: 699, originalPrice: 999, category: 'men', subcategory: 'lungis', brand: 'Ramraj Cotton', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.3, reviewCount: 2345, sizes: ['Free Size'], colors: ['White & Gold', 'Cream & Gold'], inStock: true, featured: false, tags: ['mundu', 'kerala', 'kasavu', 'cotton', 'temple'] },
    { name: 'Silk Dhoti with Border', description: 'Pure silk dhoti with contrast zari border. Essential for South Indian weddings and puja ceremonies.', price: 2499, originalPrice: 3999, category: 'men', subcategory: 'lungis', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.6, reviewCount: 456, sizes: ['Free Size'], colors: ['White & Gold', 'White & Maroon'], inStock: true, featured: false, tags: ['dhoti', 'silk', 'wedding', 'puja', 'south-indian'] },

    // =============================================================
    //  MEN'S — FOOTWEAR & ACCESSORIES
    // =============================================================
    { name: 'Kolhapuri Leather Chappal', description: 'Handcrafted genuine leather Kolhapuri chappal. Traditional Maharashtra footwear with modern comfort sole.', price: 899, originalPrice: 1299, category: 'men', subcategory: 'footwear', brand: 'Kolhapuri Craft', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400', rating: 4.4, reviewCount: 678, sizes: ['6', '7', '8', '9', '10', '11'], colors: ['Tan', 'Brown', 'Black'], inStock: true, featured: false, tags: ['kolhapuri', 'leather', 'handcrafted', 'traditional'] },
    { name: 'Mojari Embroidered Juttis', description: 'Rajasthani mojari juttis with intricate thread embroidery. Pointed toe traditional footwear for festive occasions.', price: 1199, originalPrice: null, category: 'men', subcategory: 'footwear', brand: 'Rajwada Fashion', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400', rating: 4.3, reviewCount: 345, sizes: ['6', '7', '8', '9', '10', '11'], colors: ['Gold', 'Maroon', 'Black'], inStock: true, featured: false, tags: ['mojari', 'juttis', 'rajasthani', 'embroidered'] },

    // =============================================================
    //  KIDS — ETHNIC WEAR
    // =============================================================
    { name: 'Boys Dhoti Kurta Set', description: 'Adorable dhoti kurta set for little boys. Silk kurta with pre-stitched dhoti. Perfect for festivals, mundan and naming ceremonies.', price: 1299, originalPrice: 1899, category: 'kids', subcategory: 'kids-ethnic', brand: 'Little Manyavar', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.6, reviewCount: 567, sizes: ['1-2Y', '2-3Y', '3-4Y', '4-5Y', '5-6Y'], colors: ['Cream & Gold', 'White & Maroon', 'Blue & Gold'], inStock: true, featured: true, tags: ['dhoti-kurta', 'boys', 'festive', 'ceremony'] },
    { name: 'Girls Lehenga Choli Set', description: 'Beautiful lehenga choli for girls with mirror and border work. Includes matching dupatta. Navratri and wedding special.', price: 1599, originalPrice: 2499, category: 'kids', subcategory: 'kids-ethnic', brand: 'Little Manyavar', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.7, reviewCount: 456, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'], colors: ['Red', 'Pink', 'Orange & Green'], inStock: true, featured: true, tags: ['lehenga', 'girls', 'navratri', 'wedding'] },
    { name: 'Boys Sherwani Set', description: 'Mini sherwani set for boys with churidar. Brocade fabric with embroidered collar. Wedding-ready little gentleman.', price: 2499, originalPrice: 3999, category: 'kids', subcategory: 'kids-ethnic', brand: 'Little Manyavar', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400', rating: 4.5, reviewCount: 234, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y'], colors: ['Ivory', 'Gold', 'Wine'], inStock: true, featured: false, tags: ['sherwani', 'boys', 'brocade', 'wedding'] },
    { name: 'Girls Pattu Pavadai Set', description: 'Traditional South Indian pattu pavadai (half-saree style) for girls. Pure silk with temple border. Ideal for puja and festivals.', price: 1999, originalPrice: null, category: 'kids', subcategory: 'kids-ethnic', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.6, reviewCount: 345, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'], colors: ['Red & Gold', 'Green & Gold', 'Purple & Gold'], inStock: true, featured: false, tags: ['pattu-pavadai', 'south-indian', 'silk', 'puja'] },

    // =============================================================
    //  KIDS — CASUAL WEAR
    // =============================================================
    { name: 'Boys T-Shirt & Shorts Set', description: 'Fun printed cotton t-shirt with matching shorts. Comfortable elastic waist. Perfect for playtime and outings.', price: 699, originalPrice: 999, category: 'kids', subcategory: 'kids-casual', brand: 'Chhota Bheem', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400', rating: 4.3, reviewCount: 1234, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y'], colors: ['Blue', 'Red', 'Green'], inStock: true, featured: false, tags: ['tshirt', 'shorts', 'boys', 'casual', 'playtime'] },
    { name: 'Boys Casual Kurta & Pajama', description: 'Soft cotton kurta pajama set in block print. Comfortable daily wear for kids. Easy wash and maintain.', price: 799, originalPrice: null, category: 'kids', subcategory: 'kids-casual', brand: 'Fabindia', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.2, reviewCount: 567, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'], colors: ['White & Blue', 'Yellow & Green'], inStock: true, featured: false, tags: ['kurta', 'cotton', 'daily', 'block-print'] },
    { name: 'Girls Tunic & Legging Set', description: 'Colourful printed tunic top with solid leggings. Soft cotton jersey fabric. Comfortable school and play wear.', price: 599, originalPrice: 899, category: 'kids', subcategory: 'kids-casual', brand: 'Max Kids', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400', rating: 4.1, reviewCount: 890, sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y'], colors: ['Pink', 'Purple', 'Yellow'], inStock: true, featured: false, tags: ['tunic', 'legging', 'girls', 'comfortable'] },

    // =============================================================
    //  KIDS — FROCKS
    // =============================================================
    { name: 'Party Wear Frock with Bow', description: 'Adorable party frock in net and satin with big bow detail. Layered tutu-style skirt. Birthday party special.', price: 1299, originalPrice: 1999, category: 'kids', subcategory: 'kids-frocks', brand: 'Max Kids', image: 'https://images.unsplash.com/photo-1594463750939-ebb28c3f7f75?w=400', rating: 4.5, reviewCount: 456, sizes: ['1-2Y', '2-3Y', '3-4Y', '4-5Y', '5-6Y'], colors: ['Pink', 'Red', 'White'], inStock: true, featured: true, tags: ['frock', 'party', 'birthday', 'tutu'] },
    { name: 'Cotton Printed A-Line Frock', description: 'Casual cotton frock with all-over floral print. A-line cut with puff sleeves. Daily wear essential for girls.', price: 499, originalPrice: null, category: 'kids', subcategory: 'kids-frocks', brand: 'Chhota Bheem', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400', rating: 4.0, reviewCount: 678, sizes: ['1-2Y', '2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'], colors: ['Yellow Floral', 'Blue Floral', 'Pink Floral'], inStock: true, featured: false, tags: ['frock', 'cotton', 'floral', 'daily'] },

    // =============================================================
    //  KIDS — SETS
    // =============================================================
    { name: 'Baby Romper Gift Set', description: '3-piece baby romper gift set in organic cotton. Includes romper, bib and cap. Newborn essential.', price: 999, originalPrice: 1499, category: 'kids', subcategory: 'kids-sets', brand: 'Chhota Bheem', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400', rating: 4.7, reviewCount: 567, sizes: ['0-6M', '6-12M', '12-18M'], colors: ['Yellow', 'Pink', 'Blue'], inStock: true, featured: false, tags: ['romper', 'baby', 'organic', 'gift-set', 'newborn'] },
    { name: 'Kids Nehru Jacket Set', description: 'Stylish Nehru jacket with matching kurta and pajama. Perfect for Republic Day, Independence Day and school events.', price: 1499, originalPrice: null, category: 'kids', subcategory: 'kids-sets', brand: 'Little Manyavar', image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', rating: 4.4, reviewCount: 234, sizes: ['3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'], colors: ['Saffron & White', 'Blue & White', 'Green & White'], inStock: true, featured: false, tags: ['nehru-jacket', 'school', 'patriotic', 'formal'] },

    // =============================================================
    //  SPECIAL — LIMITED EDITION
    // =============================================================
    { name: 'Bridal Kanjeevaram Collection', description: 'Limited edition bridal Kanjeevaram with real gold zari. Museum-quality weaving from master artisans. Once in a lifetime saree.', price: 49999, originalPrice: 69999, category: 'women', subcategory: 'sarees', brand: 'Kanchivaram Silks', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400', rating: 5.0, reviewCount: 45, sizes: ['Free Size'], colors: ['Red & Gold'], inStock: false, featured: true, tags: ['limited-edition', 'bridal', 'kanjeevaram', 'gold-zari', 'heirloom'] },
    { name: 'Hand-Painted Kalamkari Saree', description: 'Rare hand-painted Kalamkari saree from Srikalahasti. Natural vegetable dyes. Each piece is unique artwork.', price: 8999, originalPrice: null, category: 'women', subcategory: 'sarees', brand: 'Handloom House', image: 'https://images.unsplash.com/photo-1614886137299-130f7b108f5c?w=400', rating: 4.8, reviewCount: 123, sizes: ['Free Size'], colors: ['Natural & Red', 'Natural & Blue'], inStock: false, featured: true, tags: ['kalamkari', 'hand-painted', 'srikalahasti', 'unique'] },
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');

        await Product.deleteMany({});
        console.log('Cleared existing products');

        const inserted = await Product.insertMany(products);
        console.log(`Seeded ${inserted.length} products`);

        const menCount = inserted.filter(p => p.category === 'men').length;
        const womenCount = inserted.filter(p => p.category === 'women').length;
        const kidsCount = inserted.filter(p => p.category === 'kids').length;
        console.log(`  Women's: ${womenCount} products`);
        console.log(`  Men's: ${menCount} products`);
        console.log(`  Kids: ${kidsCount} products`);

        await mongoose.disconnect();
        console.log('Done!');
    } catch (error) {
        console.error('Seed error:', error);
        process.exit(1);
    }
}

seed();
